env:
  global:
    - CC_TEST_REPORTER_ID=ff1f3b93d85a8d4c5eeac69794d78a9579373e21abb099a91710497dee1ce351
language: node_js
node_js:
  - "node"
cache:
  directories:
    - ~/.npm
    - node_modules

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm test
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
